import { locale, t, msg } from "../i18n";
import { strengthText } from "../domain/flourStrength";
import { useState } from 'react';
import { ArrowUpRight, Check, MagnifyingGlass, Plus, Grains as Wheat } from '@phosphor-icons/react';
import type { Flour } from '../domain/types';
import { NumberField } from './Fields';
import { SelectSheet } from './SelectSheet';
export function FlourLibrary({flours,onSelect,onAdd,selectedId}: {flours:Flour[];onSelect:(f:Flour)=>void;onAdd:(f:Flour)=>void;selectedId:string}) {
  const [query,setQuery]=useState(''); const [brand,setBrand]=useState(''); const [onlyW,setOnlyW]=useState(false);
  const [onlyGlutenFree,setOnlyGlutenFree]=useState(false);
  const [custom,setCustom]=useState(false); const [name,setName]=useState(''); const [customBrand,setCustomBrand]=useState('');
  const [customGlutenFree,setCustomGlutenFree]=useState(false);
  const [w,setW]=useState(280); const [protein,setProtein]=useState(12); const [type,setType]=useState('00');
  const [expanded,setExpanded]=useState<string|null>(null);
  const brands = [...new Set(flours.map(f=>f.brand))].sort();
  const filtered=flours.filter(f=>(!brand||f.brand===brand)&&(!onlyW||f.w!==null)&&(!onlyGlutenFree||f.glutenFree)&&`${t(f.brand)} ${t(f.name)} ${t(f.type)} ${f.glutenFree?'senza glutine gluten free':''}`.toLowerCase().includes(query.toLowerCase()));
  return <>
    <div className="page-heading library-heading">
      <div><span className="eyebrow">{t("LA DISPENSA")}</span><h1>{t("Si parte dalla farina.")}</h1><p>{t("Tocca il nome di una farina per leggerne i dettagli, poi premi «Usa» per metterla nel tuo impasto.")}</p></div>
      <div className="heading-illustration" aria-hidden="true"><Wheat weight="duotone"/><span>{t("Cerca, confronta,")}<br/>{t("scegli.")}</span></div>
    </div>
    <div className="catalog-filters"><div className="search"><MagnifyingGlass/><input aria-label={t("Cerca farina")} placeholder={t("Cerca Caputo, riso, senza glutine…")} value={query} onChange={e=>setQuery(e.target.value)}/></div><div className="filter-chips"><SelectSheet label={t("Filtra per marchio")} hideLabel className="filter-select" value={brand} options={[{value:'',label:t("Tutti i marchi")},...brands.map(b=>({value:b,label:b}))]} searchPlaceholder={t("Cerca un marchio…")} onChange={setBrand}/><label className="check-label"><input type="checkbox" checked={onlyGlutenFree} onChange={e=>setOnlyGlutenFree(e.target.checked)}/> {t("Senza glutine")}</label><label className="check-label"><input type="checkbox" checked={onlyW} onChange={e=>setOnlyW(e.target.checked)}/> {t("Solo con W dichiarato")}</label></div></div>
    <div className="results-bar"><div className="results-count" role="status">{filtered.length} {t("risultati · “n.d.” significa dato non disponibile")}</div><button className="button secondary small" aria-expanded={custom} onClick={()=>setCustom(!custom)}><Plus/> {t("Aggiungi la tua farina")}</button></div>
    {custom && <form className="panel custom-form" onSubmit={e=>{e.preventDefault();if(!name.trim()||(!customGlutenFree&&(!Number.isFinite(w)||w<50||w>500))||!Number.isFinite(protein)||protein<0||protein>30)return;onAdd({id:`custom-${crypto.randomUUID()}`,brand:customBrand.trim()||t("La mia dispensa"),name:name.trim(),type,w:customGlutenFree?null:[w,w],protein,proteinBasis:t("Etichetta inserita dall’utente"),pl:null,source:'',checkedAt:new Date().toISOString().slice(0,10),kind:customGlutenFree?'blend':['00','0','1','2',msg('Integrale'),msg('Manitoba')].includes(type)?'wheat':'other',glutenFree:customGlutenFree,usable:true,note:customGlutenFree?t("Miscela senza glutine inserita dall’utente. Segui sempre idratazione, leganti e procedimento indicati sulla confezione."):t("Dati inseriti dall’utente, non verificati. Controlla sempre la confezione e adatta assorbimento e tempi alla risposta reale dell’impasto.")});setCustom(false);setName('');}}>
      <h2>{t("Aggiungi dalla confezione")}</h2><p>{t("Copia i valori dichiarati senza ricavare il W dalle proteine. Per le miscele senza glutine il W non viene richiesto.")}</p>
      <label className="check-label"><input type="checkbox" checked={customGlutenFree} onChange={e=>setCustomGlutenFree(e.target.checked)}/> {t("Miscela certificata senza glutine")}</label>
      <div className="field-grid"><label className="field">{t("Nome")}<input required maxLength={80} value={name} onChange={e=>setName(e.target.value)} placeholder={t("Nome della farina")}/></label><label className="field">{t("Marchio")}<input maxLength={60} value={customBrand} onChange={e=>setCustomBrand(e.target.value)} placeholder={t("Il molino")}/></label><SelectSheet label={t("Tipo")} value={type} options={['00','0','1','2',msg('Integrale'),msg('Manitoba'),msg('Semola rimacinata'),msg('Farro'),msg('Riso'),msg('Mais'),msg('Grano saraceno'),msg('Miscela senza glutine')].map(t=>({value:t,label:t}))} onChange={setType}/>{!customGlutenFree&&<NumberField label={t("Forza dichiarata")} value={w} onChange={setW} min={50} max={500} unit="W"/>}<NumberField label={t("Proteine")} value={protein} onChange={setProtein} min={0} max={30} step={0.1} unit="%"/></div>
      <button className="button primary" type="submit">{t("Aggiungi al catalogo")}</button>
    </form>}
    <div className="flour-list">{filtered.map(f=><article className="flour-row" key={f.id}>
      <div className={`flour-avatar ${f.glutenFree?'gluten-free':''}`}><Wheat size={26}/></div><div className="flour-main"><span className="eyebrow">{t(f.brand)}</span><h3><button className="text-button" aria-expanded={expanded===f.id} onClick={()=>setExpanded(expanded===f.id?null:f.id)}>{t(f.name)}</button></h3><p>{t("Tipo")} {t(f.type)} {f.glutenFree&&t("· Senza glutine")} {!f.usable&&t("· Solo consultazione")}</p></div>
      <div className="flour-stat"><small>{f.wEstimate&&!f.w?t("W STIMATO"):t("FORZA")}</small><strong>{(()=>{const s=strengthText(f);return s?(s.estimated?`≈ ${s.text}`:s.text):'n.d.';})()}</strong><span>W</span></div>
      <div className="flour-stat protein"><small>{t("PROTEINE")}</small><strong>{f.protein!==null?`${f.protein.toLocaleString(locale())}%`:'n.d.'}</strong><span>{f.proteinBasis.includes('secca')?t("su s.s."):t("dichiarate")}</span></div>
      <button className={`button ${selectedId===f.id?'selected':'secondary'} use-flour`} disabled={!f.usable} onClick={()=>onSelect(f)}>{selectedId===f.id?<><Check/> {t("Scelta")}</>:t("Usa")}</button>
      {expanded===f.id&&<div className="flour-detail">{f.wEstimate&&!f.w&&<p className="w-estimate-note"><strong>{t("W stimato {range} (valore centrale {value}, confidenza {confidence}).",{range:`${f.wEstimate.min}–${f.wEstimate.max}`,value:f.wEstimate.value,confidence:f.wEstimate.confidence==="media"?t("media"):t("bassa")})}</strong> {t("Valore teorico, può essere impreciso: il produttore non dichiara il W.")} {t(f.wEstimate.method)}</p>}<p>{t(f.note) || t("Valori trascritti dalla scheda pubblica del produttore. Verifica sempre confezione e lotto acquistati.")}</p><p>{t("Proteine:")} {t(f.proteinBasis)}{t(". Elasticità P/L:")} {f.pl||t("non disponibile")}{t(". Consultazione:")} {f.checkedAt}.</p>{f.source?<a href={f.source} target="_blank" rel="noreferrer">{t("Apri la fonte ufficiale")} <ArrowUpRight/></a>:<span>{t("Dati personali, non verificati dal produttore.")}</span>}</div>}
    </article>)}</div>
    {!filtered.length&&<div className="empty-state"><MagnifyingGlass size={40}/><h2>{t("Nessuna farina trovata")}</h2><p>{t("Prova un altro nome o rimuovi i filtri.")}</p><button className="button secondary" onClick={()=>{setQuery('');setBrand('');setOnlyW(false);setOnlyGlutenFree(false);}}>{t("Azzera filtri")}</button></div>}
    <div className="catalog-intro"><Wheat size={30}/><div><strong>{flours.length} {t("farine ·")} {brands.length} {t("marchi e profili")}</strong><p>{t("In cima trovi farine generiche, miscele senza glutine e alternative come riso, mais e grano saraceno; seguono le schede dei produttori consultate il 25 settembre 2026.")}</p></div></div>
  </>;
}
