import { Check, MagnifyingGlass, X, Grains as Wheat } from '@phosphor-icons/react';
import { useEffect, useId, useMemo, useState } from 'react';
import type { Flour } from '../domain/types';

const normalize=(value:string)=>value.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();

export function FlourPicker({label,value,flours,onChange,allowEmpty=false,emptyLabel='Nessuna farina'}:{
  label:string;value:string;flours:Flour[];onChange:(id:string)=>void;allowEmpty?:boolean;emptyLabel?:string;
}){
  const id=useId();const [open,setOpen]=useState(false);const [query,setQuery]=useState('');
  const selected=flours.find(item=>item.id===value);
  const usable=useMemo(()=>flours.filter(item=>item.usable),[flours]);
  const filtered=useMemo(()=>{const needle=normalize(query.trim());const matches=needle?usable.filter(item=>normalize(`${item.brand} ${item.name} ${item.type} ${item.w?.join(' ')??''}`).includes(needle)):usable;return [...matches].sort((a,b)=>Number(b.brand==='Farina generica')-Number(a.brand==='Farina generica')).slice(0,100);},[query,usable]);
  useEffect(()=>{if(!open)return;const close=(event:KeyboardEvent)=>{if(event.key==='Escape')setOpen(false);};document.addEventListener('keydown',close);return()=>document.removeEventListener('keydown',close);},[open]);
  const choose=(next:string)=>{onChange(next);setOpen(false);setQuery('');};
  return <div className="field flour-picker-field"><label id={`${id}-label`}>{label}</label><button className="flour-picker-trigger" aria-labelledby={`${id}-label`} aria-haspopup="dialog" onClick={()=>setOpen(true)}><span className="flour-picker-icon"><Wheat/></span><span><small>{selected?.brand??'MISCELA'}</small><strong>{selected?.name??emptyLabel}</strong>{selected&&<em>Tipo {selected.type} · {selected.w?`W ${selected.w.join('–')}`:'W n.d.'}</em>}</span><MagnifyingGlass/></button>{open&&<div className="flour-picker-backdrop" onMouseDown={event=>{if(event.target===event.currentTarget)setOpen(false);}}><section className="flour-picker-sheet" role="dialog" aria-modal="true" aria-labelledby={`${id}-title`}><header><div><span className="eyebrow">SCEGLI LA FARINA</span><h2 id={`${id}-title`}>{label}</h2></div><button aria-label="Chiudi selezione farine" onClick={()=>setOpen(false)}><X/></button></header><div className="flour-picker-search"><MagnifyingGlass/><input autoFocus aria-label={`Cerca per ${label.toLowerCase()}`} placeholder="Cerca tipo 1, semola, Caputo…" value={query} onChange={event=>setQuery(event.target.value)}/></div>{!query&&<p className="flour-picker-hint">Le farine generiche sono in cima. Usale quando non trovi la marca; il W resta volutamente non dichiarato.</p>}<div className="flour-picker-results">{allowEmpty&&<button className={!value?'selected':''} onClick={()=>choose('')}><span className="flour-option-icon"><X/></span><span><small>OPZIONALE</small><strong>{emptyLabel}</strong><em>Nessuna quota aggiuntiva</em></span>{!value&&<Check weight="bold"/>}</button>}{filtered.map(item=><button key={item.id} className={item.id===value?'selected':''} onClick={()=>choose(item.id)}><span className="flour-option-icon"><Wheat/></span><span><small>{item.brand}</small><strong>{item.name}</strong><em>Tipo {item.type} · {item.w?`W ${item.w.join('–')}`:'W non disponibile'}</em></span>{item.id===value&&<Check weight="bold"/>}</button>)}</div>{filtered.length===0&&<div className="flour-picker-empty"><MagnifyingGlass/><strong>Nessun risultato</strong><span>Prova con marca, nome o tipo di farina.</span></div>}</section></div>}</div>;
}
