import { ArrowUpRight, BookOpen, Play, Drop, Snowflake, Thermometer, Grains as Wheat } from '@phosphor-icons/react';
const entries = [
  {icon:Wheat,title:'W, proteine e tipo: tre cose diverse',text:'Il tipo (00, 0, 1, 2, integrale) descrive la raffinazione; W esprime la forza misurata con l’alveografo. Le proteine aiutano a leggere una farina, ma non permettono di calcolarne W. Le proteine su sostanza secca non sono direttamente confrontabili con i grammi per 100 g riportati in etichetta.'},
  {icon:Snowflake,title:'Il frigo rallenta, non mette in pausa',text:'Fermentazione e maturazione sono processi diversi che avvengono insieme. Il freddo rallenta l’attività del lievito, senza fermarla subito: una massa grande impiega tempo a raffreddarsi. Misura la temperatura del frigorifero dove appoggi il contenitore.'},
  {icon:Thermometer,title:'L’orologio guida. L’impasto decide.',text:'Una cucina calda accelera la crescita. Prima della stesura cerca panetti rilassati, ariosi e ancora capaci di mantenere la forma. Se l’impasto collassa, diventa molto appiccicoso o si lacera facilmente, può essere andato troppo avanti: anticipa la lavorazione e riduci i tempi alla prova successiva.'},
  {icon:Drop,title:'Più acqua richiede più controllo',text:'Il 70% di idratazione significa 700 g di acqua per 1 kg di farina. Non è il valore di assorbimento misurato in laboratorio. Con l’autolisi breve mescoli prima farine e parte dell’acqua per 30 minuti, senza lievito e sale; sciogli poi il lievito nell’acqua di riserva e incorporala gradualmente. Se sei all’inizio, usa la parte bassa dell’intervallo dello stile.'},
  {icon:BookOpen,title:'Diretto, poolish, biga e lievito naturale',text:'La puntata è il riposo in massa, lo staglio divide l’impasto e l’appretto è il riposo finale. Poolish e biga aggiungono una fase precedente. Per pasta madre e licoli l’app sottrae dal totale la farina e l’acqua già presenti nella coltura; gli orari restano indicativi perché la vitalità dipende dal rinfresco.'},
];
const glossary = [
  ['Idratazione','Quanta acqua metti ogni 100 g di farina. 65% significa 650 g d’acqua per 1 kg di farina.'],
  ['W (forza)','Quanto è “forte” una farina. Più è alto, più l’impasto regge lievitazioni lunghe.'],
  ['Puntata','Il primo riposo dell’impasto intero, subito dopo averlo impastato.'],
  ['Staglio','Il momento in cui dividi l’impasto e formi i panetti.'],
  ['Appretto','L’ultimo riposo dei panetti già formati, prima di stenderli.'],
  ['Maturazione in frigo','Riposo al freddo che rallenta la lievitazione e rende la pizza più digeribile e saporita.'],
  ['Poolish e biga','Preimpasti preparati ore prima: il poolish è liquido, la biga è asciutta e grumosa.'],
  ['Autolisi','Riposo di farina e acqua senza lievito e sale, utile con impasti molto idratati.'],
  ['Pasta madre e Li.Co.Li.','Lieviti naturali fatti di farina e acqua: la pasta madre è solida, il Li.Co.Li. è liquido.'],
];
export function Guide({onShowTutorial}:{onShowTutorial:()=>void}){return <><div className="page-heading guide-heading"><div><span className="eyebrow">UN PASSO ALLA VOLTA</span><h1>Mani in pasta, idee chiare.</h1><p>Pochi riferimenti per imparare a leggere il tuo impasto.</p></div><div className="heading-illustration" aria-hidden="true"><BookOpen weight="duotone"/><span>Osserva, capisci,<br/>migliora.</span></div></div><section className="tutorial-replay"><div><strong>Prima volta su PizzaLab?</strong><span>Rivedi in un minuto come funziona l’app.</span></div><button className="button secondary" onClick={onShowTutorial}><Play/> Rivedi il tutorial</button></section><section className="panel glossary" aria-labelledby="glossary-title"><div className="panel-title"><span className="section-icon"><BookOpen/></span><div><h2 id="glossary-title">Le parole da conoscere</h2><p>Nove termini che incontrerai nell’app, spiegati in una riga.</p></div></div><dl>{glossary.map(([term,text])=><div key={term}><dt>{term}</dt><dd>{text}</dd></div>)}</dl></section><div className="guide-list">{entries.map(e=><article className="guide-entry" key={e.title}><e.icon size={30}/><div><h2>{e.title}</h2><p>{e.text}</p></div></article>)}</div><section className="panel model-note"><span className="eyebrow">COME FACCIAMO I CONTI</span><h2>Un punto di partenza, da affinare.</h2><p>Le quantità usano le percentuali del panificatore. Il peso finale comprende tutti gli ingredienti. La dose di lievito usa un riferimento euristico di 0,18% di lievito fresco a 8 ore equivalenti e 22 °C; il secco istantaneo usa un rapporto indicativo 1:3. Poolish e biga dividono gli ingredienti della stessa formula e aggiungono una stima di maturità Q10.</p><p>La temperatura dell’acqua usa il metodo del fattore 3 con temperatura ambiente, farina, obiettivo dell’impasto e calore della lavorazione. Non misura attrito o temperatura reali: verifica sempre con un termometro.</p><p>Raffreddamento, attività del lievito e caratteristiche del lotto non sono misurati automaticamente. Gli avvisi sono indicazioni pratiche, non certificazioni del risultato. Registra ogni prova nel diario e adatta i tempi alla crescita reale.</p><p>Il catalogo raccoglie farine di marchi e molini italiani; questo non significa che tutti i grani siano coltivati in Italia. I valori mancanti restano non disponibili. Non sono presenti dati verificati sulle vendite.</p><div className="source-links"><a href="https://www.mulinopadano.it/blog/approfondimenti/migliori-farine-per-pizza/" target="_blank" rel="noreferrer">Leggere una farina · Mulino Padano <ArrowUpRight/></a><a href="https://molinovigevano.com/guide/la-pizza-in-teglia-romana/" target="_blank" rel="noreferrer">Tecnica della teglia · Molino Vigevano <ArrowUpRight/></a></div></section></>}
