import { ArrowUpRight, BookOpen, Drop, Snowflake, Thermometer, Grains as Wheat } from '@phosphor-icons/react';
const entries = [
  {icon:Wheat,title:'W, proteine e tipo: tre cose diverse',text:'Il tipo (00, 0, 1, 2, integrale) descrive la raffinazione; W esprime la forza misurata con l’alveografo. Le proteine aiutano a leggere una farina, ma non permettono di calcolarne W. Le proteine su sostanza secca non sono direttamente confrontabili con i grammi per 100 g riportati in etichetta.'},
  {icon:Snowflake,title:'Il frigo rallenta, non mette in pausa',text:'Fermentazione e maturazione sono processi diversi che avvengono insieme. Il freddo rallenta l’attività del lievito, senza fermarla subito: una massa grande impiega tempo a raffreddarsi. Misura la temperatura del frigorifero dove appoggi il contenitore.'},
  {icon:Thermometer,title:'L’orologio guida. L’impasto decide.',text:'Una cucina calda accelera la crescita. Prima della stesura cerca panetti rilassati, ariosi e ancora capaci di mantenere la forma. Se l’impasto collassa, diventa molto appiccicoso o si lacera facilmente, può essere andato troppo avanti: anticipa la lavorazione e riduci i tempi alla prova successiva.'},
  {icon:Drop,title:'Più acqua richiede più controllo',text:'Il 70% di idratazione significa 700 g di acqua per 1 kg di farina. Non è il valore di assorbimento misurato in laboratorio. Tieni da parte l’ultima acqua, incorporala gradualmente e usa pause per aiutare la struttura. Se sei all’inizio, usa la parte bassa dell’intervallo dello stile.'},
  {icon:BookOpen,title:'Puntata, staglio e appretto',text:'La puntata è il riposo in massa. Lo staglio divide l’impasto nelle porzioni finali. L’appretto è il riposo dopo la divisione. Qui il percorso prevede impasto diretto, riposo in massa, eventuale frigo in massa, divisione e appretto: biga, poolish e lievito madre richiedono modelli dedicati.'},
];
export function Guide(){return <><div className="page-heading"><div><span className="eyebrow">UN PASSO ALLA VOLTA</span><h1>Mani in pasta, idee chiare.</h1><p>Pochi riferimenti per imparare a leggere il tuo impasto.</p></div></div><div className="guide-list">{entries.map(e=><article className="guide-entry" key={e.title}><e.icon size={30}/><div><h2>{e.title}</h2><p>{e.text}</p></div></article>)}</div><section className="panel model-note"><span className="eyebrow">COME FACCIAMO I CONTI</span><h2>Un punto di partenza, da affinare.</h2><p>Le quantità usano le percentuali del panificatore. Il peso finale comprende farina, acqua, sale, olio e lievito. La dose di lievito è una stima euristica per impasto diretto, con un riferimento di 0,18% di lievito fresco a 8 ore equivalenti e 22 °C. Il secco istantaneo usa un rapporto indicativo 1:3: verifica la confezione.</p><p>Temperatura finale dell’impasto, raffreddamento, attività del lievito e caratteristiche del lotto non sono misurati dall’app. Gli avvisi sono indicazioni pratiche, non certificazioni del risultato. Registra ogni prova nel diario e adatta i tempi alla crescita reale.</p><p>Il catalogo raccoglie farine di marchi e molini italiani; questo non significa che tutti i grani siano coltivati in Italia. I valori mancanti restano non disponibili. Non sono presenti dati verificati sulle vendite.</p><div className="source-links"><a href="https://www.mulinopadano.it/blog/approfondimenti/migliori-farine-per-pizza/" target="_blank" rel="noreferrer">Leggere una farina · Mulino Padano <ArrowUpRight/></a><a href="https://molinovigevano.com/guide/la-pizza-in-teglia-romana/" target="_blank" rel="noreferrer">Tecnica della teglia · Molino Vigevano <ArrowUpRight/></a></div></section></>}
