import { locale, t, msg } from "../i18n";
import { ArrowLeft, ArrowRight, Check, Clock, Fire, Microphone, Pause, Play, Snowflake, SpeakerHigh, Thermometer, X } from '@phosphor-icons/react';
import { useEffect, useMemo, useRef, useState } from 'react';
import type { Stage } from '../domain/types';
import { useCloseOnBack } from '../services/backNavigation';

type Drift='ok'|'fast'|'slow'|'hot'|'cold';
type WakeLockLike={release:()=>Promise<void>};
type RecognitionLike={lang:string;continuous:boolean;interimResults:boolean;onresult:((event:{results:ArrayLike<{0:{transcript:string}}>})=>void)|null;onend:(()=>void)|null;start:()=>void;stop:()=>void};
const driftAdvice:Record<Drift,[string,string]>={ok:[msg('Tutto regolare'),msg('Continua con il piano e osserva volume, elasticità e temperatura.')],fast:[msg('Impasto in anticipo'),msg('Anticipa il passaggio in frigo o lo staglio. Ricontrolla tra 20 minuti e non aspettare l’orario se la massa sta cedendo.')],slow:[msg('Impasto in ritardo'),msg('Concedi più tempo in un ambiente leggermente più tiepido. Non aggiungere lievito a impasto già formato.')],hot:[msg('Temperatura troppo alta'),msg('Ferma la lavorazione e raffredda brevemente la massa. Nelle fasi successive riduci il tempo fuori frigo.')],cold:[msg('Impasto troppo freddo'),msg('Lascialo acclimatare coperto e valuta la crescita reale prima di stagliare o stendere.')]};
const formatTime=(seconds:number)=>`${String(Math.floor(seconds/60)).padStart(2,'0')}:${String(seconds%60).padStart(2,'0')}`;

export function GuidedMode({title,stages,onClose}:{title:string;stages:Stage[];onClose:()=>void}){
  useCloseOnBack(true,onClose);
  const [index,setIndex]=useState(0);const [running,setRunning]=useState(false);const [remaining,setRemaining]=useState(0);const [drift,setDrift]=useState<Drift>('ok');const [voice,setVoice]=useState(false);const [awake,setAwake]=useState(false);const [voiceNote,setVoiceNote]=useState('');
  const wakeRef=useRef<WakeLockLike|null>(null);const recognitionRef=useRef<RecognitionLike|null>(null);const listeningRef=useRef(false);
  const stage=stages[index];const suggested=useMemo(()=>Math.max(0,Math.round((new Date(stage.until).getTime()-new Date(stage.at).getTime())/1000)),[stage]);
  useEffect(()=>{setRemaining(Math.min(suggested,45*60));setRunning(false);},[suggested,index]);
  useEffect(()=>{if(!running||remaining<=0)return;const timer=setInterval(()=>setRemaining(s=>s-1),1000);return()=>clearInterval(timer);},[running,remaining]);
  useEffect(()=>{if(!awake){void wakeRef.current?.release();wakeRef.current=null;return;}const manager=(navigator as Navigator&{wakeLock?:{request:(type:'screen')=>Promise<WakeLockLike>}}).wakeLock;if(manager)void manager.request('screen').then(lock=>{wakeRef.current=lock;}).catch(()=>setVoiceNote(t("Il telefono non consente di bloccare lo spegnimento dello schermo.")));return()=>{void wakeRef.current?.release();wakeRef.current=null;};},[awake]);
  useEffect(()=>{if(!voice||!('speechSynthesis'in window))return;window.speechSynthesis.cancel();const utterance=new SpeechSynthesisUtterance(`${stage.title}. ${stage.detail}`);utterance.lang=locale();window.speechSynthesis.speak(utterance);},[voice,index,stage.title,stage.detail]);
  useEffect(()=>()=>{listeningRef.current=false;recognitionRef.current?.stop();window.speechSynthesis?.cancel();void wakeRef.current?.release();},[]);
  const toggleVoice=()=>{if(listeningRef.current){listeningRef.current=false;recognitionRef.current?.stop();recognitionRef.current=null;setVoice(false);setVoiceNote('');return;}const speechWindow=window as unknown as {webkitSpeechRecognition?:new()=>RecognitionLike;SpeechRecognition?:new()=>RecognitionLike};const SpeechCtor=speechWindow.SpeechRecognition??speechWindow.webkitSpeechRecognition;if(!SpeechCtor){setVoiceNote(t("I comandi vocali non sono disponibili su questo dispositivo."));return;}const recognition=new SpeechCtor();recognition.lang=locale();recognition.continuous=true;recognition.interimResults=false;recognition.onresult=(event)=>{const text=event.results[event.results.length-1][0].transcript.toLowerCase();setVoiceNote(t("Hai detto: “{trim}”", { trim: text.trim() }));if(text.includes('avanti')||text.includes('completata')||text.includes('next')||text.includes('done'))setIndex(i=>Math.min(stages.length-1,i+1));else if(text.includes('indietro')||text.includes('back')||text.includes('previous'))setIndex(i=>Math.max(0,i-1));else if(text.includes('pausa')||text.includes('pause')||text.includes('stop'))setRunning(false);else if(text.includes('avvia')||text.includes('riprendi')||text.includes('start')||text.includes('resume'))setRunning(true);};recognition.onend=()=>{if(listeningRef.current)try{recognition.start();}catch{/* browser restart race */}};recognitionRef.current=recognition;listeningRef.current=true;setVoice(true);setAwake(true);recognition.start();setVoiceNote(t("Ascolto attivo: di’ avanti, indietro, avvia o pausa."));};
  const advice=driftAdvice[drift].map(line=>t(line));
  return <div className="focus-overlay guided-mode"><header><div><Clock/><span><small>{t("MODALITÀ MANI IN PASTA")}</small><strong>{title}</strong></span></div><button aria-label={t("Chiudi modalità guidata")} onClick={onClose}><X/></button></header><main><div className="hands-free-tools"><button className={awake?'selected':''} onClick={()=>setAwake(v=>!v)}><SpeakerHigh/> {awake?t("Schermo sempre acceso"):t("Tieni acceso lo schermo")}</button><button className={voice?'selected':''} onClick={toggleVoice}><Microphone/> {voice?t("Comandi vocali attivi"):t("Attiva comandi vocali")}</button>{voiceNote&&<small>{voiceNote}</small>}</div><div className="guided-top"><span>{index+1} / {stages.length}</span><div>{stages.map((_,i)=><i key={i} className={i<=index?'done':''}/>)}</div></div><div className="guided-icon">{stage.id==='bake'?<Fire/>:stage.id==='cold'?<Snowflake/>:<Clock/>}</div><span className="focus-progress">{t("FASE ATTUALE")}</span><h2>{stage.title}</h2><p className="guided-detail">{stage.detail}</p>{suggested>0&&<div className="guided-timer"><strong>{formatTime(remaining)}</strong><button onClick={()=>setRunning(v=>!v)}>{running?<><Pause/> {t("Pausa")}</>:<><Play/> {t("Avvia timer")}</>}</button></div>}<section className="live-adjust"><div><Thermometer/><strong>{t("Come sta andando?")}</strong></div><div className="drift-options"><button className={drift==='ok'?'selected':''} onClick={()=>setDrift('ok')}>{t("Regolare")}</button><button className={drift==='fast'?'selected':''} onClick={()=>setDrift('fast')}>{t("In anticipo")}</button><button className={drift==='slow'?'selected':''} onClick={()=>setDrift('slow')}>{t("In ritardo")}</button><button className={drift==='hot'?'selected':''} onClick={()=>setDrift('hot')}>{t("Troppo caldo")}</button><button className={drift==='cold'?'selected':''} onClick={()=>setDrift('cold')}>{t("Troppo freddo")}</button></div><article><strong>{advice[0]}</strong><p>{advice[1]}</p></article></section><div className="focus-actions"><button className="button secondary" disabled={index===0} onClick={()=>setIndex(i=>i-1)}><ArrowLeft/> {t("Indietro")}</button>{index<stages.length-1?<button className="button primary" onClick={()=>setIndex(i=>i+1)}>{t("Fase completata")} <ArrowRight/></button>:<button className="button primary" onClick={onClose}><Check/> {t("Terminato")}</button>}</div></main></div>;
}
