import { useEffect, useMemo, useState } from 'react';
import { ArrowRight, Bell, BookOpen, BookmarkSimple, Check, CheckCircle, ChefHat, Clock, CookingPot, Drop, Fire, Info, Leaf, Notebook, Pizza, Snowflake, Star, Trash, Warning, Grains as Wheat, X } from '@phosphor-icons/react';
import { catalog } from './data/catalog';
import { buildTimeline, calculate } from './domain/calculator';
import { localDateTime, styles } from './domain/styles';
import type { DoughConfig, Flour, Recipe, StoredState } from './domain/types';
import { NumberField, Stepper } from './components/Fields';
import { FlourLibrary } from './components/FlourLibrary';
import { Guide } from './components/Guide';
import { emptyState, readState, writeState } from './services/storage';
import { cancelReminders, scheduleReminders } from './services/notifications';

type Tab = 'impasto' | 'farine' | 'diario' | 'guida';
const nav = [{id:'impasto',label:'Il tuo impasto',icon:CookingPot},{id:'farine',label:'Farine',icon:Wheat},{id:'diario',label:'Diario',icon:Notebook},{id:'guida',label:'Impara',icon:BookOpen}] as const;
const fmt = (n:number,digits=0)=>n.toLocaleString('it-IT',{maximumFractionDigits:digits});
const dateLabel = (s:string)=>new Date(s).toLocaleString('it-IT',{weekday:'short',day:'numeric',month:'short',hour:'2-digit',minute:'2-digit'});

export default function App(){
  const [state,setState]=useState<StoredState>(emptyState); const [ready,setReady]=useState(false);
  const [tab,setTab]=useState<Tab>('impasto'); const [message,setMessage]=useState('');
  const [storageError,setStorageError]=useState(''); const [loadError,setLoadError]=useState(false);
  const [busy,setBusy]=useState(false); const [now,setNow]=useState(Date.now());
  const [recipeName,setRecipeName]=useState(''); const [deleteId,setDeleteId]=useState<string|null>(null);
  useEffect(()=>{let alive=true;readState().then(s=>{if(alive){setState(s);setReady(true);}}).catch(()=>{if(alive){setStorageError('Non riesco a leggere l’archivio locale. I dati esistenti non sono stati sovrascritti.');setLoadError(true);setReady(true);}});return()=>{alive=false;};},[]);
  useEffect(()=>{if(ready&&!loadError)void writeState(state).catch(()=>setStorageError('Salvataggio locale non riuscito. Mantieni aperta l’app e riprova.'));},[state,ready,loadError]);
  useEffect(()=>{const timer=setInterval(()=>setNow(Date.now()),30000);return()=>clearInterval(timer);},[]);
  const flours=useMemo(()=>[...catalog,...state.customFlours],[state.customFlours]);
  const c=state.config; const selectedFlour=flours.find(f=>f.id===c.flourId);
  const result=useMemo(()=>calculate(c,flours),[c,flours]);
  const timeline=useMemo(()=>buildTimeline(c),[c]);
  const active=state.recipes.find(r=>r.id===state.activeId);
  const activeNext=active?buildTimeline(active.config).find(s=>new Date(s.at).getTime()>now):undefined;
  function update<K extends keyof DoughConfig>(key:K,value:DoughConfig[K]){setState(s=>({...s,config:{...s.config,[key]:value}}));}
  function changeStyle(id:string){const style=styles.find(s=>s.id===id)!;setState(s=>({...s,config:{...s.config,styleId:id,hydration:style.hydration,ballWeight:style.ballWeight,salt:style.salt,oil:style.oil,coldHours:style.cold,bulkHours:style.bulk,proofHours:style.proof,ovenTemp:style.oven}}));}
  function selectFlour(f:Flour){update('flourId',f.id);setTab('impasto');setMessage(`${f.brand} ${f.name} selezionata.`);window.scrollTo({top:0});}
  async function saveRecipe(){
    if(!result.ok||loadError)return;
    const recipe:Recipe={id:crypto.randomUUID(),name:recipeName.trim()||`${result.style.name} · ${new Date(c.bakeAt).toLocaleDateString('it-IT',{day:'numeric',month:'short'})}`,createdAt:new Date().toISOString(),config:{...c},notes:'',rating:0,completedStages:[]};
    const next={...state,recipes:[recipe,...state.recipes]};
    try{await writeState(next);setState(next);setMessage('Piano salvato nel diario. Puoi attivare i promemoria dalla sua scheda.');setTab('diario');}catch{setStorageError('Piano non salvato: memoria locale non disponibile.');}
  }
  async function activate(recipe:Recipe){setBusy(true);try{const note=await scheduleReminders(recipe);setState(s=>({...s,activeId:recipe.id}));setMessage(note);}catch(e){setState(s=>({...s,activeId:null}));setMessage(e instanceof Error?e.message:'Non riesco a programmare i promemoria.');}finally{setBusy(false);}}
  async function deactivate(){setBusy(true);try{await cancelReminders();setState(s=>({...s,activeId:null}));setMessage('Piano disattivato e promemoria cancellati.');}catch{setMessage('Cancellazione dei promemoria non riuscita. Riprova.');}finally{setBusy(false);}}
  async function deleteRecipe(id:string){setBusy(true);try{if(state.activeId===id)await cancelReminders();setState(s=>({...s,recipes:s.recipes.filter(r=>r.id!==id),activeId:s.activeId===id?null:s.activeId}));setDeleteId(null);}catch{setMessage('Non riesco a cancellare i promemoria. Il piano è stato conservato.');}finally{setBusy(false);}}
  function editRecipe(id:string,patch:Partial<Recipe>){setState(s=>({...s,recipes:s.recipes.map(r=>r.id===id?{...r,...patch}:r)}));}
  const isPan=styles.find(s=>s.id===c.styleId)?.pan;
  const startPast=timeline.length>0&&new Date(timeline[0].at).getTime()<now;
  if(!ready)return <div className="loading"><Pizza size={44}/><p>Prepariamo il banco…</p></div>;
  return <div className="app-shell">
    <aside className="sidebar"><a href="#impasto" className="brand" onClick={e=>{e.preventDefault();setTab('impasto');}}><span className="brand-icon"><Pizza weight="fill" size={25}/></span><span>Pizz<span className="brand-amico">Amico</span><small>LA PIZZA, INSIEME.</small></span></a><nav aria-label="Navigazione principale">{nav.map(n=><button key={n.id} className={tab===n.id?'active':''} aria-current={tab===n.id?'page':undefined} onClick={()=>{setTab(n.id);window.scrollTo({top:0});}}><n.icon size={22} weight={tab===n.id?'fill':'regular'}/><span>{n.label}</span>{n.id==='diario'&&state.recipes.length>0&&<small>{state.recipes.length}</small>}</button>)}</nav><div className="sidebar-bottom"><Leaf size={21}/><p>Farina, acqua, tempo.<br/><strong>Il resto lo impariamo insieme.</strong></p><span>Dati sul tuo dispositivo · Senza account</span></div></aside>
    <div className="workspace"><header className="topbar"><span>Il tuo compagno di impasti</span><div><span className="offline-dot"/> Disponibile offline su Android</div></header>
      <main>
      {storageError&&<div className="notice warning" role="alert"><Warning/><div>{storageError}{loadError&&<p>Ricarica l’app per riprovare. Il salvataggio è sospeso per proteggere l’archivio.</p>}</div></div>}
      {message&&<div className="toast" role="status"><Info size={22}/><p>{message}</p><button aria-label="Chiudi messaggio" onClick={()=>setMessage('')}><X/></button></div>}
      {tab==='impasto'&&<>
        <div className="page-heading"><div><span className="eyebrow">IL PIACERE DI FARLA A CASA</span><h1>La prossima pizza?<br/><span>La fai tu.</span></h1><p>Scegli lo stile. Al tuo impasto ci pensiamo insieme.</p></div><div className="heading-illustration" aria-hidden="true"><Pizza weight="duotone"/><span>Una buona pizza<br/>comincia da qui.</span></div></div>
        {active&&<button className="active-banner" onClick={()=>setTab('diario')}><Clock size={25}/><div><strong>{active.name}</strong><span>{activeNext?`Prossima fase: ${activeNext.title} · ${dateLabel(activeNext.at)}`:'La tabella di marcia è terminata. Com’è andata?'}</span></div><ArrowRight/></button>}
        <section className="style-section"><div className="section-title"><h2>Che pizza ti va?</h2><span>Ogni stile, il suo impasto</span></div><div className="style-options">{styles.map((s,i)=><button key={s.id} className={`style-option ${c.styleId===s.id?'is-selected':''}`} aria-pressed={c.styleId===s.id} onClick={()=>changeStyle(s.id)}><span className={`style-art art-${i}`} aria-hidden="true">{s.pan?<CookingPot weight="duotone"/>:<Pizza weight="duotone"/>}</span><strong>{s.name}</strong><small>{s.pan?'Da condividere':i===2?'Sottile e croccante':i===1?'Alta e ariosa':i===4?'Leggera e croccante':i===5?'Soffice e dorata':'Il grande classico'}</small>{c.styleId===s.id&&<CheckCircle className="style-check" weight="fill"/>}</button>)}</div></section>
        {result.ok&&<div className="mobile-dose" aria-label="Dosi rapide"><div><small>FARINA</small><strong>{fmt(result.flour)} <span>g</span></strong></div><div><small>ACQUA</small><strong>{fmt(result.water)} <span>g</span></strong></div><div><small>LIEVITO</small><strong>{fmt(result.yeast,2)} <span>g</span></strong></div><button aria-label="Vai alla ricetta completa" onClick={()=>document.getElementById('recipe-summary')?.scrollIntoView({behavior:'auto',block:'start'})}><ArrowRight/></button></div>}
        <div className="planner-grid"><div className="planner-fields">
          <section className="panel"><div className="panel-title"><span className="section-icon"><Wheat/></span><div><h2>La base giusta</h2><p>Farina e quantità, come piacciono a te.</p></div></div>
            <label className="field">La tua farina<select value={c.flourId} onChange={e=>update('flourId',e.target.value)}>{flours.filter(f=>f.usable).map(f=><option key={f.id} value={f.id}>{f.brand} · {f.name}{f.w?` — W ${f.w[0]}${f.w[1]!==f.w[0]?`–${f.w[1]}`:''}`:''}</option>)}</select></label>
            <div className="flour-selected-meta"><span>{selectedFlour?.w?`W ${selectedFlour.w.join('–')}`:'W non disponibile'}</span><span>{selectedFlour?.protein!==null&&selectedFlour?.protein!==undefined?`${fmt(selectedFlour.protein,1)}% proteine`:'Proteine n.d.'}</span><button onClick={()=>setTab('farine')}>Esplora le farine <ArrowRight/></button></div>
            <div className="field-grid quantity-fields"><Stepper label={isPan?'Numero di teglie':'Numero di pizze'} value={c.count} onChange={v=>update('count',v)} min={1} max={30}/>{!isPan&&<NumberField label="Peso del panetto" value={c.ballWeight} onChange={v=>update('ballWeight',v)} min={100} max={2000} step={10} unit="g"/>}</div>
            {isPan&&<div className="field-grid"><NumberField label="Larghezza teglia" value={c.panWidth} onChange={v=>update('panWidth',v)} min={10} max={80} unit="cm"/><NumberField label="Lunghezza teglia" value={c.panLength} onChange={v=>update('panLength',v)} min={10} max={100} unit="cm"/><NumberField label="Impasto per superficie" value={c.panDensity} onChange={v=>update('panDensity',v)} min={0.3} max={1} step={0.05} unit="g/cm²" hint="0,6 è un punto di partenza; aumenta per una pizza più alta."/></div>}
            <div className="hydration-field"><label htmlFor="hydration">Idratazione <strong>{fmt(c.hydration,1)}<small>%</small></strong></label><input id="hydration" type="range" min="45" max="90" value={c.hydration} onChange={e=>update('hydration',Number(e.target.value))}/><div className="range-labels"><span>Più facile da lavorare</span><span>Più ariosa</span></div></div>
            <details><summary>Sale, olio e miscela di farine</summary><div className="field-grid details-content"><NumberField label="Sale sulla farina" value={c.salt} onChange={v=>update('salt',v)} min={0} max={4} step={0.1} unit="%"/><NumberField label="Olio sulla farina" value={c.oil} onChange={v=>update('oil',v)} min={0} max={10} step={0.1} unit="%"/><label className="field">Seconda farina<select value={c.secondFlourId} onChange={e=>{update('secondFlourId',e.target.value);if(!e.target.value)update('secondFlourPercent',0);}}><option value="">Una sola farina</option>{flours.filter(f=>f.usable).map(f=><option key={f.id} value={f.id}>{f.brand} · {f.name}</option>)}</select></label>{c.secondFlourId&&<NumberField label="Quota seconda farina" value={c.secondFlourPercent} onChange={v=>update('secondFlourPercent',v)} min={0} max={100} unit="%"/>}</div></details>
          </section>
          <section className="panel"><div className="panel-title"><span className="section-icon"><Clock/></span><div><h2>Il tempo fa la sua parte</h2><p>Impasto diretto. I ritmi li scegli tu.</p></div></div>
            <div className="method-toggle" aria-label="Metodo di maturazione"><button className={c.coldHours>0?'selected':''} aria-pressed={c.coldHours>0} onClick={()=>update('coldHours',styles.find(s=>s.id===c.styleId)!.cold)}><Snowflake/> Con passaggio in frigo</button><button className={c.coldHours===0?'selected':''} aria-pressed={c.coldHours===0} onClick={()=>update('coldHours',0)}><Leaf/> Tutto fuori frigo</button></div>
            <div className="time-fields"><NumberField label="Puntata fuori frigo" value={c.bulkHours} onChange={v=>update('bulkHours',v)} min={0} max={24} step={0.5} unit="ore" hint="Primo riposo, in massa"/><NumberField label="Riposo in frigo" value={c.coldHours} onChange={v=>update('coldHours',v)} min={0} max={96} step={0.5} unit="ore" hint="Massa coperta al freddo"/><NumberField label="Appretto fuori frigo" value={c.proofHours} onChange={v=>update('proofHours',v)} min={0} max={24} step={0.5} unit="ore" hint="Ultimo riposo, già diviso"/></div>
            <div className="time-breakdown"><span style={{flex:Math.max(0.1,c.bulkHours)}}/><span className="cold" style={{flex:Math.max(0,c.coldHours),display:c.coldHours===0?'none':undefined}}/><span style={{flex:Math.max(0.1,c.proofHours)}}/></div><div className="time-total"><span>Tempo di fermentazione</span><strong>{result.ok?fmt(result.hours,1):'—'} ore <small>+ 20 min di impasto</small></strong></div>
            <div className="field-grid temperature-fields"><NumberField label="Temperatura ambiente" value={c.roomTemp} onChange={v=>update('roomTemp',v)} min={10} max={35} unit="°C"/>{c.coldHours>0&&<NumberField label="Temperatura del frigo" value={c.fridgeTemp} onChange={v=>update('fridgeTemp',v)} min={1} max={12} unit="°C"/>}<label className="field">Lievito<select value={c.yeast} onChange={e=>update('yeast',e.target.value as DoughConfig['yeast'])}><option value="fresh">Di birra fresco</option><option value="instant">Secco istantaneo</option></select></label><NumberField label="Temperatura del forno" value={c.ovenTemp} onChange={v=>update('ovenTemp',v)} min={180} max={500} step={10} unit="°C"/></div>
          </section>
          <section className="panel"><div className="panel-title"><span className="section-icon"><Fire/></span><div><h2>Quando si mangia?</h2><p>Da qui costruiamo la tua tabella di marcia.</p></div></div><label className="field">Giorno e ora della prima infornata<input type="datetime-local" value={c.bakeAt} onChange={e=>update('bakeAt',e.target.value)}/></label><button className="link-button" onClick={()=>{if(result.ok)update('bakeAt',localDateTime(new Date(Date.now()+(result.hours*60+21)*60000)));}}>Voglio cominciare a impastare adesso <ArrowRight/></button>
            {startPast&&<div className="notice warning"><Warning/><div><strong>L’inizio del piano è già passato</strong><p>Sposta la cottura in avanti o riduci i tempi per poter seguire tutte le fasi.</p></div></div>}
            <div className="timeline">{timeline.map(stage=><div className={`timeline-item ${stage.id==='cold'?'is-cold':''}`} key={stage.id}><div className="timeline-point">{stage.id==='bake'?<Fire/>:stage.id==='cold'?<Snowflake/>:<Check size={12}/>}</div><div><strong>{stage.title}</strong><span>{dateLabel(stage.at)}</span><p>{stage.detail}</p></div></div>)}</div>
          </section>
        </div>
        <aside className="recipe-sidebar" id="recipe-summary"><div className="recipe-sheet"><span className="eyebrow">IL TUO IMPASTO</span><div className="recipe-title"><h2>{styles.find(s=>s.id===c.styleId)?.name}</h2><Pizza size={35} weight="duotone"/></div><p>{result.ok?`${c.count} ${isPan?'teglie':'panetti'} da ${fmt(result.unitWeight)} g`:'Completa i valori del piano'}</p>
          {result.ok?<><div className="recipe-badges"><span><Drop/>{fmt(c.hydration,1)}%</span><span><Clock/>{fmt(result.hours,1)} h</span><span><Fire/>{c.ovenTemp} °C</span></div><div className="ingredients">{[
            ['Farina totale',result.flour,0],['Acqua',result.water,0],['Sale',result.salt,1],['Lievito '+(c.yeast==='fresh'?'fresco':'secco'),result.yeast,2],...(result.oil>0?[['Olio',result.oil,1]]:[]),
          ].map(([label,value,digits])=><div key={label}><span>{label}</span><strong>{fmt(Number(value),Number(digits))}<small> g</small></strong></div>)}</div>{c.secondFlourPercent>0&&<p className="blend-note">Miscela: {fmt(result.firstFlour)} g della prima farina + {fmt(result.secondFlour)} g della seconda. W indicativo: {result.w===null?'n.d.':fmt(result.w)}.</p>}<div className="total-weight"><span>Impasto totale</span><strong>{fmt(result.total)} g</strong></div><div className="yeast-note"><Info/><span>Lievito stimato: verifica la crescita reale. Le quantità mostrate sono arrotondate.</span></div><label className="field recipe-name">Nome del piano<input maxLength={80} value={recipeName} onChange={e=>setRecipeName(e.target.value)} placeholder="Es. La pizza del sabato"/></label><button className="button primary full" disabled={loadError} onClick={()=>void saveRecipe()}><BookmarkSimple/> Salva il piano <ArrowRight/></button><p className="save-hint">Lo ritrovi nel diario, anche offline.</p></>:<div className="notice warning" role="alert"><Warning/><div><strong>Controlla questi valori</strong><ul>{result.errors.map(e=><li key={e}>{e}</li>)}</ul></div></div>}
        </div>
        {result.ok&&<div className="advice-section"><div className="section-title"><h3><ChefHat/> Il consiglio di PizzAmico</h3></div>{result.advice.length===0?<div className="advice info"><CheckCircle/><div><strong>Un buon punto di partenza</strong><p>I parametri rientrano nei riferimenti del calcolatore. Osserva comunque l’impasto durante la lievitazione.</p></div></div>:result.advice.map(a=><div key={a.id} className={`advice ${a.level}`}>{a.level==='warning'?<Warning/>:<Info/>}<div><strong>{a.title}</strong><p>{a.text}</p></div></div>)}<div className="style-tip"><Leaf/><p>{result.style.tip}</p></div><small className="bake-note">{result.style.bake} I tempi dipendono da forno, supporto e condimento.</small></div>}
        </aside></div>
      </>}
      {tab==='farine'&&<FlourLibrary flours={flours} selectedId={c.flourId} onSelect={selectFlour} onAdd={f=>{setState(s=>({...s,customFlours:[...s.customFlours,f]}));setMessage('Farina personale aggiunta.');}}/>}
      {tab==='guida'&&<Guide/>}
      {tab==='diario'&&<><div className="page-heading"><div><span className="eyebrow">OGNI IMPASTO INSEGNA QUALCOSA</span><h1>Il tuo diario di pizza.</h1><p>Ricette, promemoria e piccoli progressi.</p></div><button className="button primary" onClick={()=>setTab('impasto')}>Nuovo impasto <ArrowRight/></button></div>{state.recipes.length===0?<div className="empty-state"><Notebook size={52} weight="duotone"/><h2>La prima pagina è tutta tua.</h2><p>Salva un piano, segui le fasi e annota com’è andata.<br/>La prossima pizza partirà da qui.</p><button className="button primary" onClick={()=>setTab('impasto')}>Prepara il primo impasto <ArrowRight/></button></div>:<div className="journal-list">{state.recipes.map(recipe=>{
        const r=calculate(recipe.config,flours);const stages=buildTimeline(recipe.config);const isActive=state.activeId===recipe.id;const expired=new Date(recipe.config.bakeAt).getTime()<=now;
        return <article className={`journal-card ${isActive?'active-recipe':''}`} key={recipe.id}><div className="journal-title"><div><span className="eyebrow">{isActive?'PIANO ATTIVO':expired?'DA RICORDARE':'IN PROGRAMMA'}</span><h2>{recipe.name}</h2><p>{dateLabel(recipe.config.bakeAt)} · {recipe.config.count} {r.ok&&r.style.pan?'teglie':'pizze'} · {recipe.config.hydration}% acqua</p></div><button className="icon-button" aria-label={`Elimina ${recipe.name}`} onClick={()=>setDeleteId(recipe.id)}><Trash/></button></div>
          {r.ok&&<div className="journal-ingredients">Farina {fmt(r.flour)} g · Acqua {fmt(r.water)} g · Sale {fmt(r.salt,1)} g · Lievito {recipe.config.yeast==='fresh'?'fresco':'secco'} {fmt(r.yeast,2)} g{r.oil>0?` · Olio ${fmt(r.oil,1)} g`:''}<br/><small>{flours.find(f=>f.id===recipe.config.flourId)?.brand} · {flours.find(f=>f.id===recipe.config.flourId)?.name}</small></div>}
          <div className="journal-actions"><button className="button secondary" onClick={()=>{setState(s=>({...s,config:{...recipe.config}}));setTab('impasto');setRecipeName(recipe.name);}}>Apri nel calcolatore</button>{isActive?<button className="button secondary" disabled={busy} onClick={()=>void deactivate()}><Bell/> Disattiva piano</button>:<button className="button primary" disabled={busy||expired} onClick={()=>void activate(recipe)}><Bell/> Attiva piano e promemoria</button>}</div>
          {isActive&&<p className="small-muted">Un solo piano attivo alla volta. Riattivarlo sostituisce i promemoria precedenti. Nel browser è disponibile solo il piano visivo.</p>}
          <details open={isActive}><summary>Le fasi del tuo impasto</summary><div className="checklist">{stages.map(stage=><label key={stage.id}><input type="checkbox" checked={recipe.completedStages.includes(stage.id)} onChange={e=>editRecipe(recipe.id,{completedStages:e.target.checked?[...recipe.completedStages,stage.id]:recipe.completedStages.filter(id=>id!==stage.id)})}/><span><strong>{stage.title}</strong><small>{dateLabel(stage.at)}</small><p>{stage.detail}</p></span></label>)}</div></details>
          <div className="recipe-review"><span>Com’è venuta?</span><div className="stars">{[1,2,3,4,5].map(n=><button key={n} aria-label={`${n} stelle per ${recipe.name}`} aria-pressed={recipe.rating===n} onClick={()=>editRecipe(recipe.id,{rating:recipe.rating===n?0:n})}><Star weight={recipe.rating>=n?'fill':'regular'}/></button>)}</div></div><label className="field">Appunti per la prossima volta<textarea rows={3} maxLength={4000} placeholder="Com’era l’impasto? Cosa cambieresti?" value={recipe.notes} onChange={e=>editRecipe(recipe.id,{notes:e.target.value})}/></label>
        </article>;
      })}</div>}</>}
      <footer className="page-footer"><span>PizzAmico</span> Fatto per chi ama mettere le mani in pasta.</footer>
      </main>
    </div>
    {deleteId&&<div className="dialog-backdrop"><div className="dialog" role="alertdialog" aria-modal="true" aria-labelledby="delete-title"><h2 id="delete-title">Eliminare questo piano?</h2><p>Verranno rimossi ricetta, appunti e gli eventuali promemoria attivi.</p><div><button autoFocus className="button secondary" onClick={()=>setDeleteId(null)}>Conserva</button><button className="button danger" disabled={busy} onClick={()=>void deleteRecipe(deleteId)}>Elimina piano</button></div></div></div>}
  </div>;
}
